moira_2.0_support (#2)
moira-alert/python-moira-client pull request #3
Opened 2017-11-06 10:21 UTC by kamaev

- Changed {'X-Webauth-User': login} to custom headers support
- Added trigger creation by custom id
- Removed tags extra data addition feature
- Changed ttl type from string to int
- Optimized fetch_by_id for large production solutions

2017-11-06 15:04 UTC, kamaev commented
Ready for review

2017-11-20 07:04 UTC, beevee requested changes

2017-11-20 07:04 UTC, beevee commented on moira_client/client.py
> -        self.auth_header = {'X-Webauth-User': login}
А какая причина у этого изменения? У нас же захардкожено в API имя этого заголовка, его нельзя поменять.

2017-11-20 07:04 UTC, beevee commented on moira_client/models/trigger.py
> +        :param expression: str golang expression
Тут C-like expression лучше написать.

2017-11-20 07:04 UTC, beevee commented on moira_client/models/trigger.py
> +        :param expression: str golang expression
Тут тоже.

2017-12-01 08:06 UTC, kamaev commented on moira_client/client.py
> -        self.auth_header = {'X-Webauth-User': login}
Исправил

2017-12-01 08:06 UTC, kamaev commented on moira_client/models/trigger.py
> +        :param expression: str golang expression
Исправил

2017-12-01 08:06 UTC, kamaev commented on moira_client/models/trigger.py
> +        :param expression: str golang expression
Исправил

2017-12-06 17:37 UTC, merged